name: ServerUtils
version: 1.1
main: prevent.msg.BlockMsgVanish
api-version: '26.2'
description: Utility Plugin for Paper
author: Arkterion Labs
website: https://arkterion.com
softdepend: [SuperVanish, PremiumVanish]
